server {
  listen 80;
  listen [::]:80;
  server_name api.app.astrochitra.com;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;
  http2 on;
  server_name api.app.astrochitra.com;

  ssl_certificate /etc/letsencrypt/live/api.app.astrochitra.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/api.app.astrochitra.com/privkey.pem;

  root /var/www/astrochitra-app/server/public;

  access_log /var/log/nginx/api.app.astrochitra.com.access.log main;
  error_log /var/log/nginx/api.app.astrochitra.com.error.log;

  client_max_body_size 10M;

  include /etc/nginx/global_settings;
  add_header Cache-Control no-transform;

  index index.php;

  location ^~ /.well-known {
    auth_basic off;
    allow all;
  }

  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }

  location ~ [^/]\.php(/|$) {
    fastcgi_pass 127.0.0.1:9002;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param SCRIPT_NAME $fastcgi_script_name;
    fastcgi_param REQUEST_METHOD $request_method;
    fastcgi_param QUERY_STRING $query_string;
    fastcgi_param REQUEST_URI $request_uri;
    fastcgi_param DOCUMENT_ROOT $document_root;
    fastcgi_param SERVER_NAME $server_name;
    fastcgi_param HTTPS on;
    fastcgi_read_timeout 300;
  }

  location ~ /\.ht {
    deny all;
  }

  location /data {
    deny all;
  }
}