import { createTranslatedProxy } from "@/content/languageStore";

export const ORDINAL_SLUGS = [
  "first", "second", "third", "fourth", "fifth",
  "sixth", "seventh", "eighth", "ninth", "tenth",
  "eleventh", "twelfth"
];

const _HOUSES = [
  { number: 1, icon: "I", title: "First House Ascendant", sanskrit: "जन्म स्थान · Birth / Central Place", tags: ["Identity", "Body", "Prestige"], shortDesc: "The foundation of self. It governs physical appearance, personality, immunity, and how the world perceives you the mirror of the soul.", governs: ["Physical appearance, body structure & health", "Personality traits, nature & immunity", "Social respect, honor & prestige", "Fortune and destiny"], deeper: "Called the Ascendant (Lagna), it is the seed of life and the starting point of the horoscope. Not just about looks it speaks to inner strength and recognition." },
  { number: 2, icon: "II", title: "Second House Wealth & Family", sanskrit: "धन / कुटुंब स्थान · Wealth / Family Place", tags: ["Wealth", "Family", "Speech"], shortDesc: "The storehouse of resources what you inherit, earn, and sustain. Speech itself is treated as a form of wealth in traditional thought.", governs: ["Wealth, financial condition & possessions", "Immovable property land & houses", "Gold, coins & valuables", "Family matters, food habits & speech", "Physical traits teeth, lips, hair", "Partnerships marital or business"], deeper: "Wealth is not just money here it encompasses relationships, values, and voice. Communication is seen as a resource equal to material prosperity." },
  { number: 3, icon: "III", title: "Third House Courage & Conflict", sanskrit: "साहस / भांडण स्थान · Courage / Conflict Place", tags: ["Courage", "Siblings", "Writing"], shortDesc: "The battlefield of personal effort where human willpower meets temptation. Bravery, creativity, and communication define this domain.", governs: ["Courage, bravery & risktaking", "Success or failure in disputes", "Writing, reading, publishing & imagination", "Diseases of the hands", "Gambling, card games & riskbased fortune", "Siblings and communication"], deeper: "Duality lives here: bravery vs recklessness, creativity vs criminal tendency. One's choices determine whether courage leads to triumph or ruin." },
  { number: 4, icon: "IV", title: "Fourth House Home & Mother", sanskrit: "मातृ स्थान · Mother's Place", tags: ["Home", "Emotions", "Property"], shortDesc: "The heart of life representing the mother, home, and emotional roots. Where you belong, both physically and spiritually.", governs: ["Happiness, peace & emotional security", "Home atmosphere & family unity", "Land, property, vehicles & children", "Education and study", "Mental beauty & emotional strength", "Influence of inlaws"], deeper: "This house holds both physical assets (land, vehicles) and emotional assets (love, unity). 'Mental beauty' reflects how it shapes inner harmony and resilience." },
  { number: 5, icon: "V", title: "Fifth House Creativity & Intellect", sanskrit: "विद्या / यांत्रिकी स्थान · Education / Creativity Place", tags: ["Education", "Children", "Romance"], shortDesc: "The seat of creativity and intellect bridging knowledge, artistic expression, romance, and spiritual wisdom.", governs: ["Education, learning & intellectual pursuits", "Children's behavior & compatibility", "Love, romance & artistic expression", "Gambling, racing & speculative wealth", "Spiritual knowledge, mantras & philosophy", "Foreign travel"], deeper: "A bridge between knowledge and faith. Risktaking in both love and finance are governed here, alongside deeper spiritual and ritual pursuits." },
  { number: 6, icon: "VI", title: "Sixth House Seasons & Disease", sanskrit: "ऋतु स्थान · Seasons / Disease Place", tags: ["Health", "Enemies", "Debts"], shortDesc: "Where life tests resilience. It governs health, conflicts, debts, and karmic obstacles yet overcoming it brings great strength.", governs: ["Health, diseases & physical troubles", "Mental stress & family conflicts", "Maternal relatives uncle, aunt", "Theft, losses & disputes", "Clothing, physical growth & restrictions", "Karmic debts"], deeper: "The house of obstacles and karmic debts. Struggles here are not punishments but invitations to build discipline and resilience." },
  { number: 7, icon: "VII", title: "Seventh House Marriage & Partnership", sanskrit: "विवाह स्थान · Marriage Place", tags: ["Marriage", "Partnership", "Contracts"], shortDesc: "The mirror of relationships governing marriage, partnerships, contracts, and all significant unions in life.", governs: ["Spouse, marriage & partnerships", "Partner's nature, character & compatibility", "Differences of opinion & disputes", "Business partnerships & trade", "Vehicles, travel & fortune through spouse", "Maternal grandmother"], deeper: "Balance is the lesson of the seventh house. It reflects how one learns through partnership and shared destiny in love, commerce, and spiritual companionship." },
  { number: 8, icon: "VIII", title: "Eighth House Death & Transformation", sanskrit: "व्यय / मोक्ष स्थान · Transformation Place", tags: ["Transformation", "Secrets", "Rebirth"], shortDesc: "The house of hidden forces governing death, rebirth, sudden change, and growth through suffering.", governs: ["Financial troubles & restrictions", "Hospitals, prisons & bondage", "Sudden losses & crises", "Hidden enemies & court cases", "Longterm diseases & spiritual practices", "Foreign travel & waterrelated illnesses"], deeper: "Though feared, the eighth house is where the deepest growth occurs. Detachment and transformation are its gifts the gateway to liberation." },
  { number: 9, icon: "IX", title: "Ninth House Dharma & Fortune", sanskrit: "धर्म स्थान · Dharma / Fortune Place", tags: ["Faith", "Wisdom", "Fortune"], shortDesc: "The pillar of faith and fortune governing religion, philosophy, higher learning, and the expansion of mind and spirit.", governs: ["Faith, religion & worship", "Respect for elders & traditions", "Success in politics & royal courts", "Foreign travel & scholarship", "Intelligence, wisdom & social service", "Father's support & guidance"], deeper: "Ethics, destiny, and divine grace reside here. Fatherly guidance and service to society are pathways to the fortune this house promises." },
  { number: 10, icon: "X", title: "Tenth House Karma & Career", sanskrit: "कर्म स्थान · Karma / Career Place", tags: ["Career", "Authority", "Legacy"], shortDesc: "The engine of action governing profession, public life, social prestige, and the legacy one builds through sustained effort.", governs: ["Father's nature & influence", "Job, profession & authority", "Stability in life & social prestige", "Politics, leadership & recognition", "Children's respect & family honor"], deeper: "Status, responsibility, and achievement converge here. How you act in the world and what you leave behind is written in the tenth house." },
  { number: 11, icon: "XI", title: "Eleventh House Gains & Friendship", sanskrit: "ग्राह स्थान · Gains / Friendship Place", tags: ["Gains", "Friends", "Prosperity"], shortDesc: "The house of aspiration and reward governing income, prosperity, social networks, and the fulfillment of desires.", governs: ["Wealth through selfeffort", "Success in job & business", "Prosperity, luxury & enjoyment", "Friends, social networks & support", "Success in elections & public life", "Father's wealth & mother's happiness"], deeper: "Material reward and emotional joy meet here. Social recognition and collective support amplify the fruits of one's efforts." },
  { number: 12, icon: "XII", title: "Twelfth House Liberation & Expense", sanskrit: "मोक्ष स्थान · Liberation / Expense Place", tags: ["Moksha", "Detachment", "Loss"], shortDesc: "The house of endings and liberation governing expenses, detachment, and the ultimate release from worldly bonds.", governs: ["Financial troubles & expenses", "Hospitals, prisons & restrictions", "Spiritual practices & detachment", "Foreign travel & waterrelated diseases", "Hidden enemies & court cases", "Death of children or relatives"], deeper: "Though associated with loss, the twelfth house is the gateway to moksha spiritual freedom. Letting go is its ultimate teaching." },
];

export const HOUSES = _HOUSES;
export const houses = createTranslatedProxy(_HOUSES);
