export interface NakshatraData {
  id: number;
  name: string;
  lord: string;
  gana: string;
  zodiac: string;
  traits: string;
  profession: string;
  auspicious: string;
}

export const NAKSHATRAS: NakshatraData[] = [
  { id: 1, name: "Ashwini", lord: "Ketu", gana: "Deva (Divine)", zodiac: "Aries",
    traits: "Quick, energetic, pioneering and healing‑oriented. Enjoys starting new ventures and helping others.",
    profession: "Traditional associations include medicine, engineering, security, literature and music.",
    auspicious: "Good for beginning journeys, marriages, new projects, surgeries and house‑warming (except Tuesdays)." },
  { id: 2, name: "Bharani", lord: "Venus", gana: "Manushya (Human)", zodiac: "Aries",
    traits: "Determined, resourceful and capable of intense effort. Values loyalty and can be protective.",
    profession: "Traditional associations include art, singing, law, fine arts and journalism.",
    auspicious: "Best for activities requiring deep commitment; avoided for brand‑new starts." },
  { id: 3, name: "Krittika", lord: "Sun", gana: "Rakshasa (Demon)", zodiac: "Aries / Taurus",
    traits: "Sharp, purifying and goal‑directed. Can be critical but also highly disciplined.",
    profession: "Traditional associations include surgery, engineering, customs, forestry and butchery.",
    auspicious: "Suitable for surgical procedures, removing toxins, and clearing obstacles." },
  { id: 4, name: "Rohini", lord: "Moon", gana: "Manushya (Human)", zodiac: "Taurus",
    traits: "Creative, nurturing and appreciative of beauty. Seeks growth, comfort and steady progress.",
    profession: "Traditional associations include art, music, agriculture, government service and gem trade.",
    auspicious: "Highly favorable for all auspicious ceremonies, marriages, house‑warming and new ventures." },
  { id: 5, name: "Mrigashira", lord: "Mars", gana: "Deva (Divine)", zodiac: "Taurus / Gemini",
    traits: "Curious, gentle and seeking knowledge. Good at research, exploration and learning.",
    profession: "Traditional associations include fine arts, medicine, dance, architecture, teaching and science.",
    auspicious: "Favorable for engagements, marriages, house‑warming, education start and vehicle purchase." },
  { id: 6, name: "Ardra", lord: "Rahu", gana: "Manushya (Human)", zodiac: "Gemini",
    traits: "Intense, transformative and mentally sharp. Can experience emotional storms leading to growth.",
    profession: "Traditional associations include medicine, accounting, teaching, photography and research.",
    auspicious: "Generally avoided for new beginnings; good for deep investigative or therapeutic work." },
  { id: 7, name: "Punarvasu", lord: "Jupiter", gana: "Deva (Divine)", zodiac: "Gemini / Cancer",
    traits: "Optimistic, renewing and generous. Embraces second chances and fresh perspectives.",
    profession: "Traditional associations include singing, music, engineering, medicine, teaching and writing.",
    auspicious: "Good for thread ceremony, education start, naming, travel and vehicle purchase." },
  { id: 8, name: "Pushya", lord: "Saturn", gana: "Deva (Divine)", zodiac: "Cancer",
    traits: "Nourishing, disciplined and protective. Provides support and structure to others.",
    profession: "Traditional associations include government, judiciary, law, farming, gold/silver trade and politics.",
    auspicious: "Excellent for building, buying gold/silver, starting shops, education and rituals; not for marriage." },
  { id: 9, name: "Ashlesha", lord: "Mercury", gana: "Rakshasa (Demon)", zodiac: "Cancer",
    traits: "Penetrating, strategic and adaptable. Can be secretive but also deeply insightful.",
    profession: "Traditional associations include writing, business, arts, music, dance and politics.",
    auspicious: "Usually avoided for auspicious events; useful for research, uncovering hidden matters and healing." },
  { id: 10, name: "Magha", lord: "Ketu", gana: "Rakshasa (Demon)", zodiac: "Leo",
    traits: "Proud, tradition‑respecting and authoritative. Connected to lineage and legacy.",
    profession: "Traditional associations include government, police, military, medicine and fire services.",
    auspicious: "Good for marriages, digging wells, education start, post‑birth rituals and surgeries." },
  { id: 11, name: "Purva Phalguni", lord: "Venus", gana: "Manushya (Human)", zodiac: "Leo",
    traits: "Enjoyable, creative and generous. Likes comfort, arts and harmonious relationships.",
    profession: "Traditional associations include sports, surgery, customs, police and military.",
    auspicious: "Suitable for digging wells and beginning education." },
  { id: 12, name: "Uttara Phalguni", lord: "Sun", gana: "Manushya (Human)", zodiac: "Leo / Virgo",
    traits: "Reliable, noble and service‑oriented. Values contracts, partnerships and long‑term commitments.",
    profession: "Traditional associations include administration, accounting, writing, farming and law.",
    auspicious: "Auspicious for marriage, upanayana, construction, temple work, sowing and education." },
  { id: 13, name: "Hasta", lord: "Moon", gana: "Deva (Divine)", zodiac: "Virgo",
    traits: "Skillful, practical and healing‑minded. Good with hands, details and service.",
    profession: "Traditional associations include medicine, law, teaching, banking, art and editing.",
    auspicious: "Favorable for marriage, naming, ear‑piercing, agriculture, new shop, wells and vastu." },
  { id: 14, name: "Chitra", lord: "Mars (Mangal)", gana: "Rakshasa (Demon)", zodiac: "Virgo / Libra",
    traits: "Artistic, precise and ambitious. Enjoys creating beauty and refining form.",
    profession: "Traditional associations include goldsmith, diamond cutting, sculpture, perfumery and luxury goods.",
    auspicious: "Good for new clothes/jewellery, arts education, wells, surgery and building." },
  { id: 15, name: "Swati", lord: "Rahu", gana: "Deva (Divine)", zodiac: "Libra",
    traits: "Independent, balanced and adaptable. Values freedom, fairness and movement.",
    profession: "Traditional associations include art, business, law, education and large corporate roles.",
    auspicious: "Favorable for marriage, house‑warming, vehicle purchase, education and new shop." },
  { id: 16, name: "Vishakha", lord: "Jupiter", gana: "Rakshasa (Demon)", zodiac: "Libra / Scorpio",
    traits: "Goal‑driven, intense and transformative. Pursues objectives with focused energy.",
    profession: "Traditional associations include teaching, law, construction, government and private sector.",
    auspicious: "Generally not for auspicious starts; good for digging, agriculture, fire rituals and adoption." },
  { id: 17, name: "Anuradha", lord: "Saturn", gana: "Deva (Divine)", zodiac: "Scorpio",
    traits: "Devoted, disciplined and cooperative. Builds lasting friendships and networks.",
    profession: "Traditional associations include painting, medicine, singing, jewellery, architecture and farming.",
    auspicious: "Highly auspicious for all holy works, marriage, naming, travel and new clothes." },
  { id: 18, name: "Jyeshtha", lord: "Mercury", gana: "Rakshasa (Demon)", zodiac: "Scorpio",
    traits: "Authoritative, protective and strategic. Can be intense but also wise.",
    profession: "Traditional associations include surgery, intelligence, law, manufacturing and high administration.",
    auspicious: "Avoided for ceremonies; suitable for occult study, surgery, land work and mantra practice." },
  { id: 19, name: "Mool", lord: "Ketu", gana: "Rakshasa (Demon)", zodiac: "Sagittarius",
    traits: "Root‑seeking, transformative and philosophical. Digs to the core of matters.",
    profession: "Traditional associations include medicine, engineering, police, military, politics and preaching.",
    auspicious: "Favorable for auspicious work, wells, mantra sadhana, medicinal planting, surgery and marriage." },
  { id: 20, name: "Purvashadha", lord: "Venus", gana: "Manushya (Human)", zodiac: "Sagittarius",
    traits: "Optimistic, expansive and victory‑oriented. Enjoys learning and sharing knowledge.",
    profession: "Traditional associations include small business, salaried work, banking and junior law.",
    auspicious: "Suitable for aggressive actions, poison work, wells, travel and agriculture." },
  { id: 21, name: "Uttarashadha", lord: "Sun", gana: "Manushya (Human)", zodiac: "Sagittarius / Capricorn",
    traits: "Steady, principled and universally victorious. Values integrity and long‑term success.",
    profession: "Traditional associations include banking, factories, railways and government offices.",
    auspicious: "Good for education, coronations, travel, marriage, naming and thread ceremony." },
  { id: 22, name: "Shravana", lord: "Moon", gana: "Deva (Divine)", zodiac: "Capricorn",
    traits: "Attentive, learning‑focused and service‑minded. Listens deeply and transmits wisdom.",
    profession: "Traditional associations include accounting, small industry, farming, priesthood and trading.",
    auspicious: "Excellent for all auspicious tasks, marriage, agriculture, sowing and rituals." },
  { id: 23, name: "Dhanishta", lord: "Mars", gana: "Rakshasa (Demonic)", zodiac: "Capricorn / Aquarius",
    traits: "Rhythmic, prosperous and collaborative. Blends effort with good timing.",
    profession: "Traditional associations include law, wholesale trade, industry and distribution.",
    auspicious: "Favorable for naming, wells, jewellery, sowing, dance, first union, adoption and building." },
  { id: 24, name: "Shatabhisha", lord: "Rahu", gana: "Rakshasa (Demonic)", zodiac: "Aquarius",
    traits: "Healing, scientific and unconventional. Seeks hidden knowledge and cures.",
    profession: "Traditional associations include specialists, medicine, architecture, law, science and economics.",
    auspicious: "Good for buying/building houses, temple work, coronation, surgery and ear/nose piercing." },
  { id: 25, name: "Purva Bhadrapada", lord: "Jupiter", gana: "Manushya (Human)", zodiac: "Aquarius / Pisces",
    traits: "Spiritual, intense and transformative. Bridges material and mystical realms.",
    profession: "Traditional associations include government, banking, railways and middle‑class retail.",
    auspicious: "Not special for muhurta; good for wells, business, travel and agriculture." },
  { id: 26, name: "Uttara Bhadrapada", lord: "Saturn", gana: "Manushya (Human)", zodiac: "Pisces",
    traits: "Stable, compassionate and disciplined. Supports others through steady effort.",
    profession: "Traditional associations include mid‑level work, insurance, travel, prisons and government.",
    auspicious: "Good for all work: building, gardening, marriage, wells, new bride entry and agriculture." },
  { id: 27, name: "Revati", lord: "Mercury", gana: "Deva (Divine)", zodiac: "Pisces",
    traits: "Nurturing, completing and protective. Brings journeys to a gentle close.",
    profession: "Traditional associations include banking, government, airlines, tourism, vegetables and beauty.",
    auspicious: "Auspicious for ceremonies, medicinal planting, arts, building, marriage and new clothes." }
];

export function getNakshatraByName(name: string) {
  return NAKSHATRAS.find(n => n.name === name);
}

export function getNakshatraById(id: number) {
  return NAKSHATRAS.find(n => n.id === id);
}