import { createTranslatedProxy } from "@/content/languageStore";

const _RASHIS = [
  {
    id: 1,
    name: "Aries",
    sanskritName: "Mesh",
    image: "/astro_icons/signs/Aries.svg",
    lord: "Mars (Mangal)",
    nature: "Movable (Char)",
    gender: "Masculine (Purush)",
    element: "Fire",
    guna: "Rajas",
    varna: "Kshatriya",
    nakshatras: "Ashwini, Bharani, Krittika (1st Charan)",
    personality: "Muscular body, courageous disposition, high-achieving, ambitious, tendency to dominate and exercise authority, hot-tempered nature, and a habit of making quick, impulsive decisions.",
    friendlySigns: "Leo, Sagittarius",
    symbol: "The Ram",
    vedicContext: "In Sanskrit, Mesha translates to a ram. In the cosmic representation of the universe (Kalapurusha), Mesha represents the head. Ruled by Mars (Mangal), the planet of energy, it symbolizes initiation, vital force, and a pioneering spirit. The ram\u2019s horns represent determination, defense, and the willingness to confront obstacles head-on. From Vedic roots, it denotes the primal fire of creation (Agni) that sparks new life.",
    represents: "Head, bold initiative, raw energy, leadership",
    profile: [
      { label: "Lord", value: "Mars (Mangal)" },
      { label: "Nature", value: "Movable (Char)" },
      { label: "Gender", value: "Masculine (Purush)" },
      { label: "Element", value: "Agni \u2022 Fire" },
      { label: "Guna", value: "Rajas" },
      { label: "Varna", value: "Kshatriya" },
      { label: "Nakshatras", value: "Ashwini, Bharani, Krittika (1st)" },
      { label: "Symbol", value: "The Ram" },
      { label: "Friendly Signs", value: "Leo, Sagittarius" },
      { label: "Kalapurusha", value: "Head" },
    ],
    traits: "Natural-born leaders with fierce determination and boundless energy. Aries natives charge ahead where others hesitate, driven by an innate need to initiate, compete, and conquer. Their honesty is refreshing but their impulsiveness can leave wreckage behind.",
  },
  {
    id: 2,
    name: "Taurus",
    sanskritName: "Vrishabh",
    image: "/astro_icons/signs/Taurus.svg",
    lord: "Venus (Shukra)",
    nature: "Fixed (Sthir)",
    gender: "Feminine (Stree)",
    element: "Earth",
    guna: "Rajas",
    varna: "Vaishya",
    nakshatras: "Krittika (2nd-4th Charan), Rohini, Mrigashira (1st-2nd Charan)",
    personality: "Physically and mentally strong, highly hardworking, patient and tolerant, with special proficiency in undertaking labor-intensive tasks and building lasting material security.",
    friendlySigns: "Virgo, Capricorn",
    symbol: "The Bull",
    vedicContext: "Vrishabha means bull. In Indian agrarian society, the bull has always been a symbol of hard labor, agricultural abundance, and fertility. It is closely associated with Nandi, the sacred mount (Vahana) of Lord Shiva, representing strength, devotion, and immense patience. Ruled by Venus (Shukra), it represents the grounded element of Earth, symbolizing stability, endurance, productivity, and material security.",
    represents: "Throat, senses, wealth, beauty, endurance",
    profile: [
      { label: "Lord", value: "Venus (Shukra)" },
      { label: "Nature", value: "Fixed (Sthir)" },
      { label: "Gender", value: "Feminine (Stree)" },
      { label: "Element", value: "Prithvi \u2022 Earth" },
      { label: "Guna", value: "Rajas" },
      { label: "Varna", value: "Vaishya" },
      { label: "Nakshatras", value: "Krittika, Rohini, Mrigashira" },
      { label: "Symbol", value: "The Bull" },
      { label: "Friendly Signs", value: "Virgo, Capricorn" },
      { label: "Kalapurusha", value: "Face & Throat" },
    ],
    traits: "Grounded, patient, and deeply sensual. Taurus natives build empires brick by brick, trusting only what they can touch, taste, and feel. They are fiercely loyal, deeplyattached to comfort, and possess an unshakeable will once set on a course.",
  },
  {
    id: 3,
    name: "Gemini",
    sanskritName: "Mithun",
    image: "/astro_icons/signs/Gemini.svg",
    lord: "Mercury (Budh)",
    nature: "Dual (Dwisvabhavy)",
    gender: "Masculine (Purush)",
    element: "Air",
    guna: "Sattva",
    varna: "Shudra",
    nakshatras: "Mrigashira (3rd-4th Charan), Ardra, Punarvasu (1st-3rd Charan)",
    personality: "An intellectual sign, slender build, sharp intelligence, cheerful and affectionate disposition, and a lover of travel and new experiences.",
    friendlySigns: "Libra, Aquarius",
    symbol: "A Couple (Man with Club and Woman with Veena)",
    vedicContext: "In Vedic tradition, Mithuna represents a young couple symbolizing the dual polarity of nature\u2014the masculine (Purusha) and feminine (Prakriti) energies. Ruled by Mercury (Budh), it represents communication, interaction, and intellectual exchange. The man holding a club signifies protection and action, while the woman holding a musical instrument represents art, creativity, and intellect.",
    represents: "Arms, communication, intellect, adaptability",
    profile: [
      { label: "Lord", value: "Mercury (Budh)" },
      { label: "Nature", value: "Dual (Dwisvabhavy)" },
      { label: "Gender", value: "Masculine (Purush)" },
      { label: "Element", value: "Vayu \u2022 Air" },
      { label: "Guna", value: "Sattva" },
      { label: "Varna", value: "Shudra" },
      { label: "Nakshatras", value: "Mrigashira, Ardra, Punarvasu" },
      { label: "Symbol", value: "The Twins" },
      { label: "Friendly Signs", value: "Libra, Aquarius" },
      { label: "Kalapurusha", value: "Arms & Shoulders" },
    ],
    traits: "Quick-witted, curious, and endlessly versatile. Gemini natives are the great communicators of the zodiac, weaving words and ideas with effortless duality. Their minds move at lightning speed, gathering knowledge from every corner of experience.",
  },
  {
    id: 4,
    name: "Cancer",
    sanskritName: "Karka",
    image: "/astro_icons/signs/Cancer.svg",
    lord: "Moon (Chandra)",
    nature: "Movable (Char)",
    gender: "Feminine (Stree)",
    element: "Water",
    guna: "Sattva",
    varna: "Vipra (Brahmin)",
    nakshatras: "Punarvasu (4th Charan), Pushya, Ashlesha",
    personality: "Highly emotional, philanthropic and benevolent nature, virtuous, honest, with deep inclination toward social work, politics, and nurturing others.",
    friendlySigns: "Scorpio, Pisces",
    symbol: "The Crab",
    vedicContext: "Karka means crab. Ruled by the Moon (Chandra), which governs the mind, maternal instincts, and emotional patterns. A crab lives both in water (emotions) and on land (physical reality). It carries its home on its back and retreats inside when threatened, representing a strong protective instinct for family, deep attachment to roots, and a sensitive, intuitive nature beneath a protective outer shell.",
    represents: "Chest, heart, emotions, home, motherhood",
    profile: [
      { label: "Lord", value: "Moon (Chandra)" },
      { label: "Nature", value: "Movable (Char)" },
      { label: "Gender", value: "Feminine (Stree)" },
      { label: "Element", value: "Jala \u2022 Water" },
      { label: "Guna", value: "Sattva" },
      { label: "Varna", value: "Vipra (Brahmin)" },
      { label: "Nakshatras", value: "Punarvasu, Pushya, Ashlesha" },
      { label: "Symbol", value: "The Crab" },
      { label: "Friendly Signs", value: "Scorpio, Pisces" },
      { label: "Kalapurusha", value: "Chest & Heart" },
    ],
    traits: "Deeply emotional, nurturing, and fiercely protective. Cancer natives carry their world within them like the crab carries its shell. Their intuition runs like an underground river, sensing moods and unspoken truths before anyone else in the room.",
  },
  {
    id: 5,
    name: "Leo",
    sanskritName: "Simha",
    image: "/astro_icons/signs/Leo.svg",
    lord: "Sun (Ravi)",
    nature: "Fixed (Sthir)",
    gender: "Masculine (Purush)",
    element: "Fire",
    guna: "Rajas",
    varna: "Kshatriya",
    nakshatras: "Magha, Purva Phalguni, Uttara Phalguni (1st Charan)",
    personality: "Dignified and imposing personality, confident and firm disposition, leadership qualities, ambitious for power, and excellent immunity and vitality.",
    friendlySigns: "Aries, Sagittarius",
    symbol: "The Lion",
    vedicContext: "Simha means lion. In Indian culture, the lion is the King of the Forest (Vanaraja) and the sacred vehicle (Vahana) of Goddess Durga, symbolizing courage, righteousness (Dharma), and protective power. Ruled by the Sun (Surya), the soul of the cosmos, Simha represents leadership, dignity, authority, and self-realization.",
    represents: "Heart, spine, leadership, self-expression, authority",
    profile: [
      { label: "Lord", value: "Sun (Ravi)" },
      { label: "Nature", value: "Fixed (Sthir)" },
      { label: "Gender", value: "Masculine (Purush)" },
      { label: "Element", value: "Agni \u2022 Fire" },
      { label: "Guna", value: "Rajas" },
      { label: "Varna", value: "Kshatriya" },
      { label: "Nakshatras", value: "Magha, P. Phalguni, U. Phalguni" },
      { label: "Symbol", value: "The Lion" },
      { label: "Friendly Signs", value: "Aries, Sagittarius" },
      { label: "Kalapurusha", value: "Heart & Spine" },
    ],
    traits: "Regal, warm, and magnanimously generous. Leo natives are born to shine, drawing others into their orbit with effortless charisma. Their courage is not performative\u2014it is a deep, Solar conviction that the world is better when they lead it boldly.",
  },
  {
    id: 6,
    name: "Virgo",
    sanskritName: "Kanya",
    image: "/astro_icons/signs/Virgo.svg",
    lord: "Mercury (Budh)",
    nature: "Dual (Dwisvabhavy)",
    gender: "Feminine (Stree)",
    element: "Earth",
    guna: "Sattva",
    varna: "Vaishya",
    nakshatras: "Uttara Phalguni (2nd-4th Charan), Hasta, Chitra (1st-2nd Charan)",
    personality: "Highly intelligent, service-oriented attitude, discerning nature, fond of detailed work, and well-suited for business, analysis, and commerce.",
    friendlySigns: "Taurus, Capricorn",
    symbol: "A Maiden in a Boat (Holding Grain and a Lamp)",
    vedicContext: "Kanya translates to a young maiden depicted sitting in a boat, carrying ears of grain in one hand and a fire lamp (Deepa) in the other. Ruled by Mercury (Budh), this sign represents purity, service, and discrimination (Viveka). The boat represents traversing the ocean of material existence; the grain signifies nourishment and practical skills; and the lamp symbolizes knowledge and analytical clarity.",
    represents: "Stomach, intestines, analysis, service, purification",
    profile: [
      { label: "Lord", value: "Mercury (Budh)" },
      { label: "Nature", value: "Dual (Dwisvabhavy)" },
      { label: "Gender", value: "Feminine (Stree)" },
      { label: "Element", value: "Prithvi \u2022 Earth" },
      { label: "Guna", value: "Sattva" },
      { label: "Varna", value: "Vaishya" },
      { label: "Nakshatras", value: "U. Phalguni, Hasta, Chitra" },
      { label: "Symbol", value: "The Maiden" },
      { label: "Friendly Signs", value: "Taurus, Capricorn" },
      { label: "Kalapurusha", value: "Stomach & Intestines" },
    ],
    traits: "Precise, analytical, and quietly indispensable. Virgo natives are the editors of the cosmos\u2014refining, perfecting, and serving with quiet brilliance. Their minds are meticulous instruments, sorting chaos into elegant order with every task they touch.",
  },
  {
    id: 7,
    name: "Libra",
    sanskritName: "Tula",
    image: "/astro_icons/signs/Libra.svg",
    lord: "Venus (Shukra)",
    nature: "Movable (Char)",
    gender: "Masculine (Purush)",
    element: "Air",
    guna: "Rajas",
    varna: "Shudra",
    nakshatras: "Chitra (3rd-4th Charan), Swati, Vishakha (1st-3rd Charan)",
    personality: "Medium height, bright and expressive eyes, skilled in debates and arguments, practical and business-minded disposition with a deep sense of fairness.",
    friendlySigns: "Gemini, Aquarius",
    symbol: "The Balance (Scales)",
    vedicContext: "Tula means a scale or balance. It is the only inanimate symbol in the zodiac. In Vedic thought, the scales represent Dharma (cosmic justice and order) and the marketplace where deeds are weighed. Ruled by Venus (Shukra), Tula represents harmony, justice, and reciprocity in relationships. It symbolizes the search for equilibrium between material desires and spiritual growth.",
    represents: "Waist, kidneys, balance, partnerships, diplomacy",
    profile: [
      { label: "Lord", value: "Venus (Shukra)" },
      { label: "Nature", value: "Movable (Char)" },
      { label: "Gender", value: "Masculine (Purush)" },
      { label: "Element", value: "Vayu \u2022 Air" },
      { label: "Guna", value: "Rajas" },
      { label: "Varna", value: "Shudra" },
      { label: "Nakshatras", value: "Chitra, Swati, Vishakha" },
      { label: "Symbol", value: "The Scales" },
      { label: "Friendly Signs", value: "Gemini, Aquarius" },
      { label: "Kalapurusha", value: "Waist & Kidneys" },
    ],
    traits: "Charming, diplomatic, and aesthetically refined. Libra natives are the diplomats of the zodiac, instinctively seeking harmony in every room they enter. Their gift is seeing both sides\u2014and their challenge is choosing one without losing the other.",
  },
  {
    id: 8,
    name: "Scorpio",
    sanskritName: "Vrishchik",
    image: "/astro_icons/signs/Scorpio.svg",
    lord: "Mars (Mangal)",
    nature: "Fixed (Sthir)",
    gender: "Feminine (Stree)",
    element: "Water",
    guna: "Tamas",
    varna: "Vipra (Brahmin)",
    nakshatras: "Vishakha (4th Charan), Anuradha, Jyeshtha",
    personality: "Emotional and gentle disposition, hot-tempered but focused and goal-oriented, patient and composed even in the most adverse situations.",
    friendlySigns: "Cancer, Pisces",
    symbol: "The Scorpion",
    vedicContext: "Vrishchik translates to a scorpion. In Vedic astrology, it corresponds to the 8th house of the cosmic man, dealing with transformation, hidden energies, and rebirth. Ruled by Mars (Mangal) and associated with Ketu, the scorpion represents intense, deep-seated energy. Its sting represents painful transformations that lead to spiritual purification and regeneration, similar to the awakening of Kundalini energy.",
    represents: "Reproductive organs, transformation, hidden depths, secrecy",
    profile: [
      { label: "Lord", value: "Mars (Mangal)" },
      { label: "Nature", value: "Fixed (Sthir)" },
      { label: "Gender", value: "Feminine (Stree)" },
      { label: "Element", value: "Jala \u2022 Water" },
      { label: "Guna", value: "Tamas" },
      { label: "Varna", value: "Vipra (Brahmin)" },
      { label: "Nakshatras", value: "Vishakha, Anuradha, Jyeshtha" },
      { label: "Symbol", value: "The Scorpion" },
      { label: "Friendly Signs", value: "Cancer, Pisces" },
      { label: "Kalapurusha", value: "Reproductive Organs" },
    ],
    traits: "Intense, magnetic, and unafraid of the dark. Scorpio natives peer beneath surfaces where others see only reflections. Their emotional depth is both their greatest power and their most demanding teacher\u2014nothing half-measured exists in their world.",
  },
  {
    id: 9,
    name: "Sagittarius",
    sanskritName: "Dhanu",
    image: "/astro_icons/signs/Sagittarius.svg",
    lord: "Jupiter (Guru)",
    nature: "Dual (Dwisvabhavy)",
    gender: "Masculine (Purush)",
    element: "Fire",
    guna: "Sattva",
    varna: "Kshatriya",
    nakshatras: "Mula, Purva Ashadha, Uttara Ashadha (1st Charan)",
    personality: "Good physique, broad forehead, bright and expressive eyes, ambitious, lover of truth, principled attitude, and deeply fond of traveling and exploration.",
    friendlySigns: "Aries, Leo",
    symbol: "The Archer (Centaur with Bow aimed at the Sky)",
    vedicContext: "Dhanu means a bow. The symbol is a Centaur pulling an arrow directed toward the sky. Ruled by Jupiter (Guru), the planet of wisdom and philosophy, it signifies focus, target-driven action, and the pursuit of truth (Satya). The horse-half represents primal strength and earthly power, while the human-half represents higher intellect aiming the arrow of awareness toward spiritual heights.",
    represents: "Thighs, higher wisdom, dharma, exploration, philosophy",
    profile: [
      { label: "Lord", value: "Jupiter (Guru)" },
      { label: "Nature", value: "Dual (Dwisvabhavy)" },
      { label: "Gender", value: "Masculine (Purush)" },
      { label: "Element", value: "Agni \u2022 Fire" },
      { label: "Guna", value: "Sattva" },
      { label: "Varna", value: "Kshatriya" },
      { label: "Nakshatras", value: "Mula, P. Ashadha, U. Ashadha" },
      { label: "Symbol", value: "The Archer" },
      { label: "Friendly Signs", value: "Aries, Leo" },
      { label: "Kalapurusha", value: "Thighs & Hips" },
    ],
    traits: "Adventurous, philosophical, and irrepressibly optimistic. Sagittarius natives aim their arrows at distant horizons, driven by an unquenchable thirst for truth, meaning, and freedom. Their faith in life\u2019s goodness is both their compass and their armor.",
  },
  {
    id: 10,
    name: "Capricorn",
    sanskritName: "Makar",
    image: "/astro_icons/signs/Capricorn.svg",
    lord: "Saturn (Shani)",
    nature: "Movable (Char)",
    gender: "Feminine (Stree)",
    element: "Earth",
    guna: "Tamas",
    varna: "Vaishya",
    nakshatras: "Uttara Ashadha (2nd-4th Charan), Shravan, Dhanishta (1st-2nd Charan)",
    personality: "Prone to health weaknesses, far-sighted and practical disposition, reserved and soft-spoken, business-savvy, and economical with resources.",
    friendlySigns: "Taurus, Virgo",
    symbol: "The Makara (Mythological Sea-Creature with Deer Head and Fish Tail)",
    vedicContext: "In Indian tradition, Makara is a mythological creature with the forequarters of a land animal and the hindquarters of an aquatic animal. It is the vehicle (Vahana) of Goddess Ganga and Varuna. Ruled by Saturn (Shani), Makara represents the transition between two realms: the land (worldly ambition) and the deep waters (the deep subconscious). It signifies patience, perseverance, and a steady climb toward mastery.",
    represents: "Knees, bones, discipline, structure, career, reputation",
    profile: [
      { label: "Lord", value: "Saturn (Shani)" },
      { label: "Nature", value: "Movable (Char)" },
      { label: "Gender", value: "Feminine (Stree)" },
      { label: "Element", value: "Prithvi \u2022 Earth" },
      { label: "Guna", value: "Tamas" },
      { label: "Varna", value: "Vaishya" },
      { label: "Nakshatras", value: "U. Ashadha, Shravan, Dhanishta" },
      { label: "Symbol", value: "The Sea-Goat" },
      { label: "Friendly Signs", value: "Taurus, Virgo" },
      { label: "Kalapurusha", value: "Knees & Bones" },
    ],
    traits: "Ambitious, disciplined, and patient beyond measure. Capricorn natives climb the mountain not for the view but because the summit demands it. They carry the weight of responsibility with quiet dignity, building legacies that outlast their own lifetimes.",
  },
  {
    id: 11,
    name: "Aquarius",
    sanskritName: "Kumbh",
    image: "/astro_icons/signs/Aquarius.svg",
    lord: "Saturn (Shani)",
    nature: "Fixed (Sthir)",
    gender: "Masculine (Purush)",
    element: "Air",
    guna: "Tamas",
    varna: "Shudra",
    nakshatras: "Dhanishta (3rd-4th Charan), Shatabhisha, Purva Bhadrapada (1st-3rd Charan)",
    personality: "Tall build, sharp intellect, analytical and research-oriented attitude, deep study habits, and excellent comprehension and investigative capabilities.",
    friendlySigns: "Gemini, Libra",
    symbol: "The Water-Bearer (Kalasha / Pitcher)",
    vedicContext: "Kumbha translates to a clay pot or pitcher. In Indian tradition, the Kumbha is a sacred vessel used in rituals to hold holy water, representing the nectar of immortality (Amrit) and cosmic knowledge. Ruled by Saturn (Shani), this sign represents the storage and distribution of wisdom. The person carrying the pot pours it out for humanity, signifying humanitarianism and sharing knowledge for the welfare of society.",
    represents: "Calves, ankles, innovation, humanitarianism, collective vision",
    profile: [
      { label: "Lord", value: "Saturn (Shani)" },
      { label: "Nature", value: "Fixed (Sthir)" },
      { label: "Gender", value: "Masculine (Purush)" },
      { label: "Element", value: "Vayu \u2022 Air" },
      { label: "Guna", value: "Tamas" },
      { label: "Varna", value: "Shudra" },
      { label: "Nakshatras", value: "Dhanishta, Shatabhisha, P. Bhadrapada" },
      { label: "Symbol", value: "The Water-Bearer" },
      { label: "Friendly Signs", value: "Gemini, Libra" },
      { label: "Kalapurusha", value: "Calves & Ankles" },
    ],
    traits: "Visionary, unconventional, and devoted to the collective good. Aquarius natives pour wisdom like water from a sacred vessel\u2014not for themselves but for humanity. Their minds are ahead of their time, building futures that others cannot yet imagine.",
  },
  {
    id: 12,
    name: "Pisces",
    sanskritName: "Meen",
    image: "/astro_icons/signs/Pisces.svg",
    lord: "Jupiter (Guru)",
    nature: "Dual (Dwisvabhavy)",
    gender: "Feminine (Stree)",
    element: "Water",
    guna: "Sattva",
    varna: "Vipra (Brahmin)",
    nakshatras: "Purva Bhadrapada (4th Charan), Uttara Bhadrapada, Revati",
    personality: "Benevolent nature, calm and pleasant disposition, student of occult and mystic sciences, peaceful life, though may experience low physical resistance.",
    friendlySigns: "Cancer, Scorpio",
    symbol: "Two Fish Swimming in Opposite Directions, Tied at Tails",
    vedicContext: "Meen means fish. In Indian mythology, the fish is associated with Matsya, the first incarnation (Avatar) of Lord Vishnu, who saved humanity and the sacred Vedas during the cosmic deluge. Ruled by Jupiter (Guru), Meen represents the final stage of the soul\u2019s journey\u2014liberation (Moksha). The two fish swimming in opposite directions represent the dual nature of human consciousness: one fish looks toward worldly illusion (Maya), while the other swims toward spiritual liberation.",
    represents: "Feet, liberation, compassion, spiritual surrender, dissolution",
    profile: [
      { label: "Lord", value: "Jupiter (Guru)" },
      { label: "Nature", value: "Dual (Dwisvabhavy)" },
      { label: "Gender", value: "Feminine (Stree)" },
      { label: "Element", value: "Jala \u2022 Water" },
      { label: "Guna", value: "Sattva" },
      { label: "Varna", value: "Vipra (Brahmin)" },
      { label: "Nakshatras", value: "P. Bhadrapada, U. Bhadrapada, Revati" },
      { label: "Symbol", value: "Two Fish" },
      { label: "Friendly Signs", value: "Cancer, Scorpio" },
      { label: "Kalapurusha", value: "Feet & Lymph" },
    ],
    traits: "Compassionate, imaginative, and spiritually attuned beyond ordinary comprehension. Pisces natives dissolve the boundaries between self and universe, channeling divine compassion through music, art, prayer, and selfless service to the suffering.",
  },
];

export const RASHIS = _RASHIS;
export const rashis = createTranslatedProxy(_RASHIS);
